const Prome=[{
    id:1,
    film_name:"The Pursuit of Happyness",
    category:"Real-life",
    image:"Image/image1.jpg",
    duration:"1h 57m",
    language:"English, Hindi, Tamil",
    Information:"Tired of Chris's professional failures, his wife decides to separate, leaving him financially broke with an unpaid internship in a brokerage firm and his son's custody to deal with.",
},
{
    id:2,
    film_name:"Death of Me",
    category:"Horror",
    image:"Image/image2.jpg",
    duration:"1h 34m",
    language:"English",
    Information:"A hungover couple makes a horrific discovery about the events of the previous night. They try to deconstruct the night to the best of their memories while waiting for a typhoon to pass.",

},
{
    id:3,
    film_name:"Free Guy",
    category:"Comedy",
    image:"Image/image3.jpg",
    duration:"1h 54m",
    language:"English, Hindi",
    Information:"When a bank teller discovers he's actually a background player in an open-world video game, he decides to become the hero of his own story -- one that he can rewrite himself.",
},
{
    id:4,
    film_name:"Dolittle",
    category:"Comedy",
    image:"Image/image4.jpg",
    duration:"1h 41m",
    language:"English, Hindi, Tamil, Urdu",
    Information:"A physician, who can speak with animals, is summoned by the queen to find a cure for her life-threatening disease. Soon, he embarks on a journey with his furry friends in search of a healing tree.",
},
{
    id:5,
    film_name:"127 Hours",
    category:"Real-life",
    image:"Image/image5.jpg",
    duration:"1h 35m",
    language:"Hindi, Tamil",
    Information:"Aron Ralston, a mountain climber, is on a hiking adventure in Utah when he gets trapped in a canyon. Soon, he takes desperate measures to survive and struggles for 127 hours before he is rescued.",

},
{
    id:6,
    film_name:"Into The Wild",
    category:"Real-life",
    image:"Image/image7.jpg",
    duration:"2h 28m",
    language:"English, Hindi, Tamil",
    Information:"Christopher McCandless, a young graduate, decides to renounce all his possessions and hitchhike across America. During his journey, he encounters several situations which change him as a person.",
},
{
    id:7,
    film_name:"The Conjuring",
    category:"Horror",
    image:"Image/image6.jpg",
    duration:"1h 52m",
    language:"English",
    Information:"The Conjuring is a 2013 American supernatural horror film directed by James Wan and written by Chad Hayes and Carey W. Hayes. It is the inaugural film in the Conjuring Universe franchise.",
},
{
    id:8,
    film_name:"Shang-Chi and The Legend of The Ten Rings",
    category:"Fantasy",
    image:"Image/image8.jpg",
    duration:"2h 12m",
    language:"English",
    Information:"Martial-arts master Shang-Chi confronts the past he thought he left behind when he's drawn into the web of the mysterious Ten Rings organization.",
},
{
    id:9,
    film_name:"Monster Hunter",
    category:"Fantasy",
    image:"Image/image9.jpg",
    duration:"1h 44m",
    language:"English, Hindi, Urdu",
    Information:"Captain Artemis and her group of soldiers are pulled into a world where dangerous monsters and humans co-exist. Grappled by danger, they must find a way to escape with help from a mysterious hunter.",
},
{
    id:10,
    film_name:"Finch",
    category:"Sci-Fi",
    image:"Image/image10.jpg",
    duration:"1h 55m",
    language:"English, Hindi, Urdu",
    Information:"A robot that lives on a post-apocalyptic earth which was built to protect the life of his dying creator's beloved dog, it learns about love, friendship, and the meaning of human life.",
},
{
    
    id:11,
    film_name:"The Meg",
    category:"Sci-Fi",
    image:"Image/image11.jpg",
    duration:"1h 53m",
    language:"English, Hindi",
    Information:"When the members of an underwater research facility are under threat owing to a 75-foot prehistoric shark, Jonas Taylor, a deep-sea diver, is hired to save them.",
},
{
    id:12,
    film_name:"Outside the Wire",
    category:"Sci-Fi",
    image:"Image/image12.jpg",
    duration:"1h 55m",
    language:"English, Hindi",
    Information:"In the near future, a drone pilot sent into a war zone finds himself paired up with a top-secret android officer on a mission to stop a nuclear attack.",
},
{
   
    id:13,
    film_name:"Tag",
    category:"Comedy",
    image:"Image/image13.jpg",
    duration:"1h 40m",
    language:"English, Hindi",
    Information:"A group of five friends, who have been playing the game of tag for 30 years, decide to play one last game before the wedding of their undefeated player",
},
{
    id:14,
    film_name:"TaHarry Potter and the Prisoner of Azkaban",
    category:"Fantasy",
    image:"Image/image14.jpg",
    duration:"2h 22m",
    language:"English, Hindi",
    Information:"Harry, Ron and Hermoine return to Hogwarts just as they learn about Sirius Black and his plans to kill Harry. However, when Harry runs into him, he learns that the truth is far from reality.",
},
{
    id:15,
    film_name:"Jungle Cruise",
    category:"Fantasy",
    image:"Image/image15.jpg",
    duration:"2h 07m",
    language:"English, Hindi",
    Information:"Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his ramshackle boat. Together, they search for an ancient tree that holds the power to heal -- a discovery that will change the future of medicine.",
},

];

export default Prome;